version: "3.8"
services:
  database:
    image: mongo
    container_name: database
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - leanbotdata:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  app: 
    build: .
    env_file:
      - ./.env.prod
    ports: 
      - 80:80
    depends_on: 
      - database
    restart: unless-stopped
volumes:
  leanbotdata: