export interface Channel {
  id: string,
  name: string,
  created: any,
  unlinked: number,
  creator: string,
  name_normalized: string,
  is_channel: boolean,
  is_archived: boolean,
  is_general: boolean,
  is_shared: boolean,
  is_org_shared: boolean,
  is_member: boolean,
  is_private: boolean,
  is_mpim: boolean,
  last_read: any,
  has_pins: boolean,
  members: any[],
  topic: any,
  purpose: any,
  previous_names: any[],
  priority: number,
}