import { User } from "../../models/slack/user";
import { UserProfile } from "../../models/slack/user-profile";

export const buildUser = ({
  id = "",
  name = "",
  team_id = "",
  deleted = false,
  color = "",
  real_name = "",
  tz = "",
  tz_label = "",
  tz_offset = 0,
  is_admin = false,
  is_owner = false,
  is_primary_owner = false,
  is_restricted = false,
  is_ultra_restricted = false,
  is_bot = false,
  is_app_user = false,
  updated = "",
  presence = "",
}: Partial<User>): User => ({
  id,
  name,
  team_id,
  deleted,
  color,
  real_name,
  tz,
  tz_label,
  tz_offset,
  profile: undefined,
  is_admin,
  is_owner,
  is_primary_owner,
  is_restricted,
  is_ultra_restricted,
  is_bot,
  is_app_user,
  updated,
  presence,
});