import { Channel } from "../../models/slack/channel";

export const buildChannel = ({
  id = "irrelevant",
  name = "irrelevant",
  created = "irrelevant",
  unlinked = 0,
  creator = "irrelevant",
  name_normalized = "irrelevant",
  is_channel = false,
  is_archived = false,
  is_general = false,
  is_shared = false,
  is_org_shared = false,
  is_member = false,
  is_private = false,
  is_mpim = false,
  last_read = "irrelevant",
  has_pins = false,
  members = [],
  topic = "irrelevant",
  purpose = "irrelevant",
  previous_names = [],
  priority = 0,
}: Partial<Channel>): Channel => ({
  id,
  name,
  created,
  unlinked,
  creator,
  name_normalized,
  is_channel,
  is_archived,
  is_general,
  is_shared,
  is_org_shared,
  is_member,
  is_private,
  is_mpim,
  last_read,
  has_pins,
  members,
  topic,
  purpose,
  previous_names,
  priority
});