name: Pull Request Tests
on:
  pull_request:
    branches:
      - master
jobs:
  tests:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: 
          - 12.16
          - 12.20
          - 14.15
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - name: Execute docker test database script for windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm run test:database-windows

      - name: Execute docker test database script for unix
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: npm run test:database-unix

      - name: Check docker containers 
        run: docker ps -a 
        
      - name: Run tests
        run: npm run test
