name: Pull Request Tests
on:
  pull_request:
    branches:
      - master
jobs:
  tests:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: 
          - 12.16
          - 12.20
          - 14.15
        mongodb-version: 
          - 4.2
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install Packages
        run: npm install
      - name: Check docker containers 
        run: docker ps -a 
      - name: Run tests
        run: npm run test
